export { default as HomePage } from "./HomePage/HomePage";
export { default as ContactPage } from "./ContactPage/ContactPage";
export { default as OrderPage } from "./OrderPage/OrderPage";
export { default as LoginPage } from "./Auth/LoginPage";
export { default as RegisterPage } from "./Auth/RegisterPage";
export { default as ResetPage } from "./Auth/ResetPage";
export { default as AdminPage } from "./AdminPage/AdminPage";
export { default as BasketPage } from "./BasketPage/BasketPage";
export { default as CheckoutDetails } from "./CheckoutPage/CheckoutDetails";
